/* ============================================================================
 * ktgmc_cpu_ref.cpp — CPU reference mirror of the KTGMC simple kernels.
 *
 * This is the *algorithm* reference used to validate the OpenCL port.  It
 * reproduces, element-for-element, the math of the CUDA kernels in
 * AviSynthCUDAFilters/KTGMC/Kernel.cu (and the host-side ResamplingProgram).
 *
 * It is intentionally scalar and single-threaded: each KTGMC simple kernel is
 * per-pixel separable, so the translation is exact regardless of vectorization.
 *
 * Build (requires only a C++17 compiler, no external libs):
 *     g++ -O2 -std=c++17 sim/ktgmc_cpu_ref.cpp -o /tmp/ktgmc_ref
 * Run:
 *     /tmp/ktgmc_ref <in_dir> <out_dir> <bitdepth 8|16>
 *
 * in_dir must contain the planes generated by python/run_validation.py:
 *     a.raw b.raw ref.raw field.raw   (raw = pitch*height*px bytes, 2-D packed)
 * in_dir/plane.info  -> one line per plane:  "name width height pitch"
 * Each plane's data is contiguous rows of `pitch` samples where only
 * `width` (<=pitch) columns are valid.
 * ==========================================================================*/
#include <cstdint>
#include <cstdio>
#include <cmath>
#include <vector>
#include <string>
#include <cstring>
#include <algorithm>
using namespace std;

/* ---------------- pixel wrappers ---------------- */
template<typename PX> constexpr int PixelMax();
template<> constexpr int PixelMax<uint8_t>(){return 255;}
template<> constexpr int PixelMax<uint16_t>(){return 65535;}

template<typename PX> struct Plane {
    int w, h, pitch;
    vector<PX> data;
    const PX& at(int x,int y) const { return data[(size_t)y*pitch+x]; }
          PX& at(int x,int y)       { return data[(size_t)y*pitch+x]; }
};

template<typename PX> bool readPlane(const string& dir,const string& name,Plane<PX>& pl){
    string infoPath=dir+"/plane.info";
    FILE* fi=fopen(infoPath.c_str(),"r"); if(!fi){perror("plane.info");return false;}
    // find line with name
    char buf[512]; int ok=0;
    while(fgets(buf,sizeof(buf),fi)){
        char nm[64]; int w,h,pt;
        if(sscanf(buf,"%63s %d %d %d",nm,&w,&h,&pt)==4 && name==nm){ok=1;pl.w=w;pl.h=h;pl.pitch=pt;break;}
    }
    fclose(fi); if(!ok)return false;
    string p=dir+"/"+name+".raw";
    FILE* f=fopen(p.c_str(),"rb"); if(!f){perror(p.c_str());return false;}
    pl.data.resize((size_t)pl.pitch*pl.h);
    if(fread(pl.data.data(),pl.pitch*pl.h,sizeof(PX),f)!=(size_t)pl.pitch*pl.h){fclose(f);return false;}
    fclose(f); return true;
}
template<typename PX> bool writePlane(const string& dir,const string& name,const Plane<PX>& pl){
    string p=dir+"/"+name+".raw";
    FILE* f=fopen(p.c_str(),"wb"); if(!f){perror(p.c_str());return false;}
    fwrite(pl.data.data(),pl.pitch*pl.h,sizeof(PX),f); fclose(f); return true;
}

/* ---------------- ResamplingProgram (host side) ---------------- */
struct ResamplingProgram {
    int filter_size=0, target_size=0;
    vector<int>    offset;
    vector<double> coef;   // coef[row*filter_size + i]
};

// Mitchell-Netravali filter, b=0 c=0.5 (Catmull-Rom) as used by KTGMC_Bob.
struct Mitchell {
    double p0,p2,p3,q0,q1,q2,q3;
    Mitchell(double b,double c){
        p0=(6.-2.*b)/6.; p2=(-18.+12.*b+6.*c)/6.; p3=(12.-9.*b-6.*c)/6.;
        q0=(8.*b+24.*c)/6.; q1=(-12.*b-48.*c)/6.; q2=(6.*b+30.*c)/6.; q3=(-b-6.*c)/6.;
    }
    double support(){return 2.0;}
    double f(double x){ x=fabs(x);
        return (x<1)?(p0+x*x*(p2+x*p3)) : (x<2)?(q0+x*(q1+x*(q2+x*q3))) : 0.0; }
};

ResamplingProgram build_resampling_program(
    int source_size, double crop_start, double crop_size, int target_size,
    double b, double c){
    Mitchell mit(b,c);
    double filter_scale = double(target_size)/crop_size;
    double filter_step  = min(filter_scale,1.0);
    double filter_support= mit.support()/filter_step;
    int fir = int(ceil(filter_support*2));
    ResamplingProgram P; P.filter_size=fir; P.target_size=target_size;
    P.offset.assign(target_size,0); P.coef.assign((size_t)target_size*fir,0.0);
    double pos, pos_step = crop_size/target_size;
    if(fir==1) pos=crop_start; else pos=crop_start+((crop_size-target_size)/(target_size*2));
    for(int i=0;i<target_size;++i){
        int end_pos=int(pos+filter_support);
        if(end_pos>source_size-1) end_pos=source_size-1;
        int start_pos=end_pos-fir+1;
        if(start_pos<0) start_pos=0;
        P.offset[i]=start_pos;
        double total=0.0;
        double ok_pos=clamp(pos,0.0,double(source_size-1));
        for(int j=0;j<fir;++j) total+=mit.f((start_pos+j-ok_pos)*filter_step);
        if(total==0.0) total=1.0;
        double value=0.0;
        for(int k=0;k<fir;++k){
            double nv=value+mit.f((start_pos+k-ok_pos)*filter_step)/total;
            P.coef[i*fir+k]=nv-value; value=nv;
        }
        pos+=pos_step;
    }
    return P;
}

/* ---------------- kernels (scalar, double-accumulate) ---------------- */
template<typename PX>
void kernel_resample_v(const Plane<PX>& src, Plane<PX>& dst,
                       const ResamplingProgram& prog){
    for(int y=0;y<dst.h;++y){
        int begin=prog.offset[y];
        for(int x=0;x<dst.w;++x){
            double acc=0.0;
            for(int i=0;i<prog.filter_size;++i)
                acc += (double)src.at(x,begin+i)*prog.coef[y*prog.filter_size+i];
            acc=clamp(acc,0.0,(double)PixelMax<PX>());
            dst.at(x,y)=(PX)(int)(acc+0.5);
        }
    }
}

template<typename PX>
void kernel_makediff(const Plane<PX>& a,const Plane<PX>& b,Plane<PX>& dst,
                     int mode,int range_half){
    for(int y=0;y<dst.h;++y)for(int x=0;x<dst.w;++x){
        int va=(int)a.at(x,y), vb=(int)b.at(x,y);
        int v=(mode==0)?(va-vb+range_half):(va+vb-range_half);
        v=clamp(v,0,PixelMax<PX>()); dst.at(x,y)=(PX)v;
    }
}

template<typename PX>
void kernel_rg_box3x3(const Plane<PX>& src,Plane<PX>& dst,int mode){
    for(int y=0;y<dst.h;++y)for(int x=0;x<dst.w;++x){
        int s=(int)src.at(x,y); int v=s;
        if(x>=1&&x<dst.w-1&&y>=1&&y<dst.h-1){
            auto g=[&](int dx,int dy)->int{return (int)src.at(x+dx,y+dy);};
            int ul=g(-1,-1),uc=g(0,-1),ur=g(1,-1);
            int ml=g(-1,0),          mr=g(1,0);
            int ll=g(-1,1),lc=g(0,1),lr=g(1,1);
            int vt;
            if(mode==20){int h0=ul+uc+ur,h1=ml+s+mr,h2=ll+lc+lr; vt=(h0+h1+h2+4)/9;}
            else        {int h0=ul+2*uc+ur,h1=ml+2*s+mr,h2=ll+2*lc+lr; vt=(h0+2*h1+h2+8)>>4;}
            v=clamp(vt,0,PixelMax<PX>());
        }
        dst.at(x,y)=(PX)v;
    }
}
static inline void sort8(int* a){
#define CAS(i,j) do{int x=a[i],y=a[j];a[i]=min(x,y);a[j]=max(x,y);}while(0)
    CAS(0,1);CAS(2,3);CAS(4,5);CAS(6,7);CAS(0,2);CAS(1,3);CAS(4,6);CAS(5,7);
    CAS(1,2);CAS(5,6);CAS(0,4);CAS(1,5);CAS(2,6);CAS(3,7);CAS(2,4);CAS(3,5);
    CAS(1,2);CAS(3,4);CAS(5,6);
#undef CAS
}
static inline void sort9(int* a){
#define CAS(i,j) do{int x=a[i],y=a[j];a[i]=min(x,y);a[j]=max(x,y);}while(0)
    CAS(0,1);CAS(3,4);CAS(6,7);CAS(1,2);CAS(4,5);CAS(7,8);CAS(0,1);CAS(3,4);
    CAS(6,7);CAS(0,3);CAS(1,4);CAS(2,5);CAS(3,6);CAS(4,7);CAS(5,8);CAS(0,3);
    CAS(1,4);CAS(2,5);CAS(1,3);CAS(5,7);CAS(2,6);CAS(4,6);CAS(2,4);CAS(2,3);
    CAS(5,6);
#undef CAS
}

template<typename PX>
void kernel_removegrain(const Plane<PX>& src,Plane<PX>& dst,int n){
    for(int y=0;y<dst.h;++y)for(int x=0;x<dst.w;++x){
        int s=(int)src.at(x,y); int v=s;
        if(x>=1&&x<dst.w-1&&y>=1&&y<dst.h-1){
            int a[8]={(int)src.at(x-1,y-1),(int)src.at(x,y-1),(int)src.at(x+1,y-1),
                      (int)src.at(x-1,y)  ,               (int)src.at(x+1,y),
                      (int)src.at(x-1,y+1),(int)src.at(x,y+1),(int)src.at(x+1,y+1)};
            sort8(a); v=clamp(s,a[n-1],a[7-(n-1)]);
        }
        dst.at(x,y)=(PX)v;
    }
}

template<typename PX>
void kernel_repair(const Plane<PX>& src,const Plane<PX>& ref,Plane<PX>& dst,int n){
    for(int y=0;y<dst.h;++y)for(int x=0;x<dst.w;++x){
        int s=(int)src.at(x,y); int v=s;
        if(x>=1&&x<dst.w-1&&y>=1&&y<dst.h-1){
            int a[9]={(int)ref.at(x-1,y-1),(int)ref.at(x,y-1),(int)ref.at(x+1,y-1),
                      (int)ref.at(x-1,y), s, (int)ref.at(x+1,y),
                      (int)ref.at(x-1,y+1),(int)ref.at(x,y+1),(int)ref.at(x+1,y+1)};
            sort9(a); v=clamp(s,a[n-1],a[8-(n-1)]);
        }
        dst.at(x,y)=(PX)v;
    }
}

template<typename PX>
void kernel_vcleaner(const Plane<PX>& src,Plane<PX>& dst){
    for(int y=0;y<dst.h;++y)for(int x=0;x<dst.w;++x){
        int b=(int)src.at(x,y); int v=b;
        if(y>=1&&y<dst.h-1){
            int a=(int)src.at(x,y-1),c=(int)src.at(x,y+1);
            v=min(max(min(a,b),c),max(a,b));
        }
        dst.at(x,y)=(PX)v;
    }
}

template<typename PX>
void kernel_to_full_range(const Plane<PX>& src,Plane<PX>& dst,int is_uv){
    for(int y=0;y<dst.h;++y)for(int x=0;x<dst.w;++x){
        double s=(double)src.at(x,y);
        double d=(is_uv)?(s-128.0)*(128.0/112.0)+128.0 : (s-16.0)*(255.0/219.0);
        d=clamp(d+0.5,0.0,(double)PixelMax<PX>()); dst.at(x,y)=(PX)(int)d;
    }
}

template<typename PX>
void kernel_merge(const Plane<PX>& a,const Plane<PX>& b,Plane<PX>& dst,int weight){
    int invweight=32767-weight;
    for(int y=0;y<dst.h;++y)for(int x=0;x<dst.w;++x){
        int v=((int)a.at(x,y)*invweight+(int)b.at(x,y)*weight+16384)>>15;
        v=clamp(v,0,PixelMax<PX>()); dst.at(x,y)=(PX)v;
    }
}

/* ---------------- driver ---------------- */
int main(int argc,char** argv){
    if(argc<4){fprintf(stderr,"usage: ref <in_dir> <out_dir> <bitdepth 8|16>\n");return 2;}
    string inDir=argv[1], outDir=argv[2];
    int bits=atoi(argv[3]);
    int maxpx = bits==8?255:65535;

    // build resample program for KTGMC_Bob doubling a 5-row field to 10 rows
    ResamplingProgram prog = build_resampling_program(5, 0.25, 5, 10, 0.0, 0.5);
    // dump for python cross-check
    {
        FILE* f=fopen((outDir+"/prog_offset.txt").c_str(),"w");
        for(int i:prog.offset)fprintf(f,"%d\n",i); fclose(f);
        FILE* g=fopen((outDir+"/prog_coef.txt").c_str(),"w");
        for(double c:prog.coef)fprintf(g,"%.17g\n",c); fclose(g);
    }

    if(bits==8){
        Plane<uint8_t> a,b,ref,field;
        readPlane(inDir,"a",a);readPlane(inDir,"b",b);readPlane(inDir,"ref",ref);readPlane(inDir,"field",field);

        auto mkout=[&](){Plane<uint8_t> o;o.w=a.w;o.h=a.h;o.pitch=a.pitch;o.data.assign((size_t)o.pitch*o.h,0);return o;};
        {auto o=mkout();kernel_makediff(a,b,o,0,128);writePlane(outDir,"makediff",o);}
        {auto o=mkout();kernel_makediff(a,b,o,1,128);writePlane(outDir,"adddiff",o);}
        {auto o=mkout();kernel_rg_box3x3(a,o,11);writePlane(outDir,"rg11",o);}
        {auto o=mkout();kernel_rg_box3x3(a,o,20);writePlane(outDir,"rg20",o);}
        for(int n=1;n<=4;++n){auto o=mkout();kernel_removegrain(a,o,n);writePlane(outDir,"rgclip"+to_string(n),o);}
        for(int n=1;n<=4;++n){auto o=mkout();kernel_repair(a,ref,o,n);writePlane(outDir,"repair"+to_string(n),o);}
        {auto o=mkout();kernel_vcleaner(a,o);writePlane(outDir,"vclean",o);}
        {auto o=mkout();kernel_to_full_range(a,o,0);writePlane(outDir,"tfr_y",o);}
        {auto o=mkout();kernel_to_full_range(a,o,1);writePlane(outDir,"tfr_uv",o);}
        {auto o=mkout();kernel_merge(a,b,o,(int)(0.5f*32767));writePlane(outDir,"merge",o);}
        {Plane<uint8_t> o;o.w=field.w;o.h=10;o.pitch=field.pitch;o.data.assign((size_t)o.pitch*o.h,0);
         kernel_resample_v(field,o,prog);writePlane(outDir,"resample_v",o);}
    } else {
        Plane<uint16_t> a,b,ref,field;
        readPlane(inDir,"a",a);readPlane(inDir,"b",b);readPlane(inDir,"ref",ref);readPlane(inDir,"field",field);
        auto mkout=[&](){Plane<uint16_t> o;o.w=a.w;o.h=a.h;o.pitch=a.pitch;o.data.assign((size_t)o.pitch*o.h,0);return o;};
        {auto o=mkout();kernel_makediff(a,b,o,0,32768);writePlane(outDir,"makediff",o);}
        {auto o=mkout();kernel_makediff(a,b,o,1,32768);writePlane(outDir,"adddiff",o);}
        {auto o=mkout();kernel_rg_box3x3(a,o,11);writePlane(outDir,"rg11",o);}
        {auto o=mkout();kernel_rg_box3x3(a,o,20);writePlane(outDir,"rg20",o);}
        for(int n=1;n<=4;++n){auto o=mkout();kernel_removegrain(a,o,n);writePlane(outDir,"rgclip"+to_string(n),o);}
        for(int n=1;n<=4;++n){auto o=mkout();kernel_repair(a,ref,o,n);writePlane(outDir,"repair"+to_string(n),o);}
        {auto o=mkout();kernel_vcleaner(a,o);writePlane(outDir,"vclean",o);}
        {auto o=mkout();kernel_to_full_range(a,o,0);writePlane(outDir,"tfr_y",o);}
        {auto o=mkout();kernel_to_full_range(a,o,1);writePlane(outDir,"tfr_uv",o);}
        {auto o=mkout();kernel_merge(a,b,o,(int)(0.5f*32767));writePlane(outDir,"merge",o);}
        {Plane<uint16_t> o;o.w=field.w;o.h=10;o.pitch=field.pitch;o.data.assign((size_t)o.pitch*o.h,0);
         kernel_resample_v(field,o,prog);writePlane(outDir,"resample_v",o);}
    }
    fprintf(stderr,"bitdepth %d done\n",bits);
    return 0;
}
